### ISSUE TITLE
[ISSUE] "Back" Button in Play Room Crashes/Closes Game

### ISSUE THREAD

**Issue by TheGitMagician** [YoYoGames/GMEXT-mod.io#2]
When you "play" a mod you enter the room rm_modio_play. It contains a back button which is supposed to bring you back to the main menu / mod overview.

Clicking this button force-closes / crashes the game.

**Comment by DiasFranciscoA** [comment]
Thank you for reaching out with the issue report,

This is now fixed in github main branch will soon be updated on the release package and on the marketplace
