### ISSUE TITLE
[ISSUE] Character Sprite Isn't Saved Correctly

### ISSUE THREAD

**Issue by TheGitMagician** [YoYoGames/GMEXT-mod.io#3]
The Create Mod menu allows for two "characters" to be added to the mod in the form of sprite strips.

However, the sprites of these characters don't get saved correctly in the uploaded mod. Instead of the drawn subframes the whole saved sprite in the mod is completely transparent.

You can see that the general mechanism of adding sprites is working correctly because the sprite strip becomes larger with each added subframe (but it's all transparent). Also the data.txt file correctly shows that there is a character that is supposed to consist of x number of subframes.

So the only issue is that the generated / uploaded sprite is completely transparent.

**Comment by DiasFranciscoA** [comment]
Thank you for reaching out with the issue report,

This is now fixed in github main branch will soon be updated on the release package and on the marketplace
